### ISSUE TITLE
Logo animation

### ISSUE THREAD

**Issue by EltarSilence** [EltarSilence/GeekChat#3]
Creazione animazione del Logo.
Entro fine giornata ho il logo pronto e te lo allego qui.

**Comment by EltarSilence** [comment]
![Logo](https://i.gyazo.com/bc51348de597442286dfd041b6f9ba3a.png)

Il vettoriale e altri formati si trovano in 

`project/GC Logo`

**Comment by Zexal0807** [comment]
Credo che il logo possa essere bianco su sfondo trasparente, senza la scritta, cosa ne dite

**Comment by EltarSilence** [comment]
Logo creato e problema risolto
