### ISSUE TITLE
MessageBar animation

### ISSUE THREAD

**Issue by EltarSilence** [EltarSilence/GeekChat#4]
Bisogna cercare un modo per animare la barra di messaggio, quando si preme la freccettina di discesa.

info: funzioni `.toggle()`, `.slideToggle()`, ecc. di jQuery.
In alternativa: rifare i `<div>`, mettendo le classi di bootstrap `collapse` dal sito.

**Comment by Zexal0807** [comment]
Mi occupo io dei toggle
